Repository jenkins-x-charts/nexus, pull requests merged in 2019-01, with the labels that each got.

#17 Update nexus base Docker Image version from 3.13.0 to 3.14.0
  Dockerfile
Labels: approved, ok-to-test, size/XS

#20 fix: configured updatebot to trigger downstream releases
  .updatebot.yml
  Jenkinsfile
Labels: approved, size/XS

#19 fix(errors) general script improvements
  Jenkinsfile
  maven-group.json
  postStart.sh
  repositories/jenkins-public.json
  repositories/jenkins-release.json
  repositories/jitpack.json
  repositories/maven-jenkinsci.json
  repositories/spring-milestone.json
  repositories/spring-release.json
Labels: approved, ok-to-test, size/M

#21 chore: upgrading to nexus 3.15.1
  Dockerfile
Labels: approved, size/XS

#23 force repfix dokcer registry to be dockerhub to avoid internal registry IP being used
  charts/nexus/values.yaml
Labels: approved, size/XS

#24 set DOCKER_REGISTRY env var
  Jenkinsfile
Labels: approved, size/XS

#25 Add some useful repositories
  maven-group.json
  repositories/gradle-distributions.json
  repositories/jenkins-public.json
  repositories/npmjs-registry.json
  repositories/plugins-gradle.json
Labels: approved, ok-to-test, size/S

#26 feat: disabling anon access after start
  disable-anonymous-access.json
  postStart.sh
Labels: approved, size/XS

#27 Adding resource requests and limits to deployment
  charts/nexus/values.yaml
Labels: approved, ok-to-test, size/S

#30 lets lower the default request
  charts/nexus/values.yaml
Labels: approved, size/XS

#31 fix: do not define the limits for resources
  charts/nexus/values.yaml
Labels: approved, size/S
