Repository jenkins-x-charts/nexus, pull requests merged in 2020-01, with the labels that each got.

#44 chore: update the pipeline file and makefile of nexus helm chart
  charts/nexus/Makefile
  jenkins-x.yml
Labels: size/L

#45 chore: fix chart path in pipeline and make files
  charts/nexus/Makefile
  jenkins-x.yml
Labels: size/M

#39 Fixup postStart.sh to handle spaces in passwords.
  postStart.sh
Labels: approved, lgtm

#42 fix: compatible with kube api 1.16+
  charts/nexus/templates/deployment.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#46 chore: update the nexus docker image to version 3.20.1
  Dockerfile
Labels: size/XS

#47 chore: updated repo config to use https
  repositories/spring-milestone.json
  repositories/spring-release.json
Labels: approved, lgtm, size/XS
